[control]
localhost ansible_connection=local

[monitored_vms]
vm-prod-01 ansible_host=172.31.46.224
vm-prod-02 ansible_host=172.31.34.199

[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/k8s-key.pem
